# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cdbc8cf022ac347200022aa1d2649ebd3ed11ab8162a75436d36dc4da216a3eddb961f221544193fb933631d9080242dd090269c06ad9dbf62c4006a20f11f2

test:
  secret_key_base: c65c95ef6710a3ffd9b93892f1635adeaf69174690353cfa2fee9dea26218167db4f26d3646bc053bef6019b81cc64b989cab07f5943daae461a3a9b12461038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
